name: Test Fail

on:
  push:
    branches:
      - main
    paths-ignore:
      - fixes/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install numpy==99.99.99